import { SandpackCSS } from "@/components/sandpack-styles";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <SandpackCSS />
      </head>
      <body>{children}</body>
    </html>
  );
}
