import { commonFiles } from "../common";

export const NEXTJS_14_TEMPLATE = {
  files: {
    ...commonFiles,
    "/app/layout.js": {
      code: `import '../styles.css'

export const metadata = {
  title: 'My App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}`,
    },
    "/app/page.js": {
      code: `export default function Home({ data }) {
  return (
    <div>
      <h1>Hello {data}</h1>
    </div>
  );
}

// In Next.js 14, async functions handle server-side fetching more effectively
export async function generateMetadata() {
  return {
    title: 'Home Page',
  };
}

export async function getServerSideProps() {
  return {
    props: { data: "world" },
  };
}`,
    },
    "/next.config.js": {
      code: `/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  swcMinify: true,
  experimental: {
    appDir: true,
  },
}

module.exports = nextConfig
`,
    },
    "/package.json": {
      code: JSON.stringify({
        name: "my-app",
        version: "0.1.0",
        private: true,
        scripts: {
          dev: "NEXT_TELEMETRY_DISABLED=1 next dev",
          build: "next build",
          start: "next start",
          lint: "next lint",
        },
        dependencies: {
          next: "^14", // Updated to Next.js 14
          react: "18.2.0",
          "react-dom": "18.2.0",
        },
      }),
    },
  },
  main: "/app/page.js",
  environment: "node",
};