import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <section>
      <Head>
        <title>Sandpack</title>
        <meta content="Generated by create next app" name="description" />
        <link href="/favicon.ico" rel="icon" />
      </Head>
      <h1>hello, world.</h1>
    </section>
  );
};

export default Home;
