name: "Chromatic"

on:
  push:
    paths:
      - "sandpack-react/src/**"

jobs:
  chromatic-deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Install dependencies and cache
        uses: bahmutov/npm-install@v1
        with:
          useLockFile: true

      - name: Build dependency
        run: yarn workspace @codesandbox/sandpack-client run build

      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          buildScriptName: "chromatic:react"
