name: "Chromatic"

on:
  push:
    paths:
      - "sandpack-react/src/**"

jobs:
  chromatic-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Get entire Git history. Required by Chromatic.

      - name: Install dependencies
        run: yarn

      - name: Build dependency
        run: yarn workspace @codesandbox/sandpack-client run build

      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          buildScriptName: "chromatic:react"
