name: Sizebot

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  integration:
    name: Sizebot
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v1

      - name: Setup | Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14.16.1"

      - name: Install dependencies and cache
        uses: bahmutov/npm-install@v1
        with:
          useLockFile: true

      - name: Setup | Build
        run: yarn run build

      - name: Bot script
        run: node scripts/sizebot/index.js
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
